Add a feature to change roman table
lambdalisue/kensaku.vim pull request #6
Opened 2023-02-10 14:04 UTC by uga-rosa

SSIA

2023-02-12 15:15 UTC, uga-rosa commented
A related commit
[ce8b04d15b5da9da4f5366ca0a8d7bfbe055c3c3](https://github.com/oguna/jsmigemo/commit/ce8b04d15b5da9da4f5366ca0a8d7bfbe055c3c3)

2023-02-14 05:51 UTC, lambdalisue requested changes
追加した関数のヘルプを書いてください

2023-02-14 05:51 UTC, lambdalisue commented on denops/kensaku/main.ts
> +    },
不要な `async` 関数化を避けるため `setRomanTable` の戻り値を直接返したうえで `async` を取り除いてください

2023-02-14 17:14 UTC, uga-rosa commented on denops/kensaku/main.ts
> +    },
これで合っていますか？

2023-02-14 17:14 UTC, uga-rosa commented
ヘルプ追加しました。

2023-02-15 03:33 UTC, lambdalisue requested changes

2023-02-15 03:33 UTC, lambdalisue commented on autoload/kensaku.vim
> +        \ -> denops#request('kensaku', 'setRomanTable', [a:romanTable]) })
返り値が不要なので代わりに `denops#notify` を利用してください

2023-02-15 03:33 UTC, lambdalisue commented on denops/kensaku/migemo.ts
> +  }
二箇所以上で使うことになるので以下の関数を定義して既存コードも置き換えてください

```ts
function getMigemo(denops: Denops): jsmigemo.Migemo {
  if (!migemo) {
    migemo = await init(denops)
  }
  return migemo;
}
```

2023-02-15 03:33 UTC, lambdalisue commented on doc/kensaku.jax
> +	ります。remainは省略可能で、その場合は0になります。
以下のように部分的に省略された具体的な使い方を書いてください（以下は 8 スペースインデントですがヘルプなのでタブで）

```vim
>
        call kensaku#set_roman_table([
              \ ["qq", "っ", 1],
              \ [ azik などをしらないので具体的な例がわからない ]
              \ ...
              \])
<
```

2023-02-15 05:23 UTC, uga-rosa commented
修正しました。

2023-02-15 06:48 UTC, lambdalisue requested changes

2023-02-15 06:48 UTC, lambdalisue commented on denops/kensaku/migemo.ts
> +  migemo = await getMigemo(denops);
ここは関数ローカル変数でお願いします

```typescript
const migemo = await getMigemo(denops);
```

2023-02-15 06:48 UTC, lambdalisue commented on denops/kensaku/migemo.ts
> +  migemo = await getMigemo(denops);
同様

2023-02-15 06:48 UTC, lambdalisue commented on doc/kensaku.jax
> +	      \ ])
ここはスペースを開けないでください

```
              \])
```

2023-02-16 07:16 UTC, uga-rosa commented
修正しました。

2023-02-16 07:24 UTC, lambdalisue approved these changes
LGTM

2023-02-16 08:09 UTC, merged